"""Hacer el campo email unico en AtenasUser y actualiza 

Revision ID: 35e9e3753c58
Revises: ad404364efd5
Create Date: 2025-08-27 08:50:59.290958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e9e3753c58'
down_revision: Union[str, Sequence[str], None] = 'ad404364efd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_atenasuser_email'), 'atenasuser', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atenasuser_email'), table_name='atenasuser')
    # ### end Alembic commands ###
