"""Añadir relaciones entre User, Order y CoffeeType

Revision ID: ad404364efd5
Revises: fd5e64842429
Create Date: 2025-08-27 08:28:56.793100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad404364efd5'
down_revision: Union[str, Sequence[str], None] = 'fd5e64842429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atenasuser', sa.Column('fecha_de_creacion', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('atenasuser', sa.Column('fecha_de_modificacion', sa.DateTime(), nullable=True, onupdate=sa.text('CURRENT_TIMESTAMP')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atenasuser', 'fecha_de_modificacion')
    op.drop_column('atenasuser', 'fecha_de_creacion')
    # ### end Alembic commands ###
