"""Agrega campo role a AtenasUser

Revision ID: f22d35cc657f
Revises: 35e9e3753c58
Create Date: 2025-08-28 08:29:20.885408

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f22d35cc657f'
down_revision: Union[str, Sequence[str], None] = '35e9e3753c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atenasuser', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False,  server_default='user'))
    op.create_index(op.f('ix_atenasuser_role'), 'atenasuser', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atenasuser_role'), table_name='atenasuser')
    op.drop_column('atenasuser', 'role')
    # ### end Alembic commands ###
